hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/studentdb
hibernate.connection.username=root
hibernate.connection.password=surya2006
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
hibernate.hbm2ddl.auto=update
hibernate.current_session_context_class=thread